socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(19688), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 4
connect(4, {sa_family=AF_INET, sin_port=htons(19689), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
write(4, "\x00\x00\x00\x01", 4) = 4
read(4, "\x00\x00\x00\x00", 4) = 4
write(4, "\x00\x00\x00\x0b", 4) = 4
read(4, "\x00\x00\x00\x00", 4) = 4
write(3, "\x00\x00\x00\x08\x03\x00\x00\x00\x0c", 9) = 9
write(3, "\x80\x01\x00\x00\x00\x0c\x00\x00\x01\x44\x00\x00", 12) = 12
read(3, "\x00\x00\x00\x0a", 4) = 4
read(3, "\x80\x01\x00\x00\x00\x0a\x00\x00\x01\x00", 10) = 10
read(3, "\x00\x00\x00\x00", 4) = 4
write(2, "ERROR:sys:src/tss2-sys/api/Tss2_Sys_Initialize.c:54:Tss2_Sys_Initialize() ABI-Version of application f0000000.2.1.108 differs from ABI version of SAPI 1.2.1.1 \n", 160) = 160
write(2, "ERROR:sys:src/tss2-sys/api/Tss2_Sys_Initialize.c:54:Tss2_Sys_Initialize() ABI-Version of application 1.4026531840.1.108 differs from ABI version of SAPI 1.2.1.1 \n", 162) = 162
write(2, "ERROR:sys:src/tss2-sys/api/Tss2_Sys_Initialize.c:54:Tss2_Sys_Initialize() ABI-Version of application 1.2.4026531840.108 differs from ABI version of SAPI 1.2.1.1 \n", 162) = 162
write(2, "ERROR:sys:src/tss2-sys/api/Tss2_Sys_Initialize.c:54:Tss2_Sys_Initialize() ABI-Version of application 1.2.1.4026531840 differs from ABI version of SAPI 1.2.1.1 \n", 160) = 160
+++ exited with 0 +++
